#!/usr/bin/env python
t= input (" entrer votre taille en cm=")
t=int (t)
m= input ("entre votre masse en kg=")
m= int (m)
y= (m)/((t/100)**2)
print ("imc=",y)

if (y < 16.5):
	print (" vous etes en sous poids")
if (16.5 < y) and (y < 18.5):
	print (" vous etes en maigreur")
if (18.5 < y) and (y < 25):
	print (" vous etes en corpulence normal")
if (25 < y) and (y < 30):
	print (" vous etes en obésité modéré")
if (30 < y) and (y < 35):
	print (" vous etes en obésité sévère")
if (35 < y) and (y < 40):
	print (" vous etes en obésité morbide")
